name: tag-version-action
description: change tag, commit, and push the change to gitops repo.
# version: 1.0.7
author: Fizgig.co
inputs:
  the_version:
    description: the version that should be in the tag
    required: true 
  file:
    description: the file that should be changed
    required: true
  commit_name:
    description: Name of the identity that is used in the commit's author signature.
    required: true
  commit_email:
    description: Email of the identity that is used in the commit's author signature.
    required: true
  commit_message:
    description: Commit message
    required: true
    default: Commit performed using Push and Commit action
  target_branch:
    description: Branch to push the changes back to
    required: true
  remote_repository:
    description: Repository url to push the code to
    required: true
  token:
    description: Token used to push the code
    required: true
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set -x
      if [ -z "${{ inputs.token }}" ]; then
        echo "WARNING: The token input is mandatory to push files to another repository."
        exit 1
      fi      
      REGEX="^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+)$"

      if [[ ${{ inputs.remote_repository }} =~ $REGEX ]]; then
          PROTOCOL=${BASH_REMATCH[1]}
          SEPARATOR=${BASH_REMATCH[2]}
          HOSTNAME=${BASH_REMATCH[3]}
          DESTINATION_OWNER=${BASH_REMATCH[4]}
          DESTINATION_REPOSITORY=${BASH_REMATCH[5]}
          if [[ $DESTINATION_REPOSITORY == *'.git'* ]] && [[ $DESTINATION_REPOSITORY != *'.github.io'* ]]; then
            DESTINATION_REPOSITORY=${DESTINATION_REPOSITORY//.git/ }
          fi

        git config --global user.name "${{ inputs.commit_name }}"
        git config --global user.email "${{ inputs.commit_email }}"
        git config --global pull.rebase false
        CLONE_DIRECTORY=$(mktemp -d)

        git clone --single-branch --branch ${{ inputs.target_branch }} "https://${{ inputs.token }}@github.com/$DESTINATION_OWNER/$DESTINATION_REPOSITORY.git" "$CLONE_DIRECTORY"

        cd $CLONE_DIRECTORY
        sed -r "s/^(\s*tag\s*:\s*).*/\1${{ inputs.the_version }}/" -i "${{ inputs.file }}"

        git add ${{ inputs.file }}

        git commit --message "${{ inputs.commit_message }}"

        git push -u origin "${{ inputs.target_branch }}"
        
        echo "##### Pushed git commit #####"
      else
        echo
        echo "WARNING: Couldn't read remote_repository URL input."
        echo "ACCEPTED FORMAT:"
        echo "git://github.com/<owner>/<repo>.git"
        echo "or"
        echo "git@github.com:<owner>/<repo>.git"
        echo "or"
        echo "https://github.com/<owner>/<repo>.git"
        echo "or"
        echo "https://github.com/<owner>/<repo>"
        exit 1
      fi
